local colors = {
  fg = "#FFFFFF",          -- Brightened from original
  bg = "#000000",          -- Kept black
  alt_fg = "#00FFFF",      -- Brightened cyan for better visibility
  alt_bg = "#222222",      -- Dark gray for alternate background
  cursorline = "#222222",  -- Matching alt_bg
  line = "#333333",        -- Slightly lighter for lines
  dark_gray = "#555555",   -- Kept original
  gray = "#888888",        -- Lightened for better visibility
  context = "#888888",     -- Lightened for better visibility
  light_gray = "#AAAAAA",  -- Kept original
  red = "#FF5555",         -- Brightened red
  blue = "#5599FF",        -- Brightened blue
  green = "#55FF55",       -- Brightened green
  cyan = "#00FFFF",        -- Brightened cyan
  orange = "#FFAA55",      -- Brightened orange
  yellow = "#FFFF55",      -- Kept original
  purple = "#FF55FF",      -- Brightened purple
  magenta = "#FF55FF",     -- Brightened magenta
  cursor_fg = "#000000",   -- Black for cursor
  cursor_bg = "#FFFFFF",   -- White for cursor
  sign_add = "#55FF55",    -- Brightened green for git add
  sign_change = "#5599FF", -- Brightened blue for git change
  sign_delete = "#FF5555", -- Brightened red for git delete
  sign_add_alt = "#55FFAA",
  sign_change_alt = "#55AAFF",
  error = "#FF5555",
  warn = "#FFAA55",
  info = "#55FF55",
  hint = "#5599FF",
  error_bg = "#331111",
  warn_bg = "#332211",
  info_bg = "#113311",
  hint_bg = "#112233",
  reference = "#333333",
  success_green = "#55FF55",
  folder_blue = "#55AAFF",
  ui_blue = "#5599FF",
  ui2_blue = "#3366CC",
  ui3_blue = "#6699FF",
  ui4_blue = "#55AAFF",
  ui5_blue = "#5555FF",
  ui_orange = "#FFAA55",
  ui2_orange = "#FF9933",
  ui_purple = "#FF55FF",
}

return colors
