local colors = {
  fg = "#FFFFFF",  -- Changed to white for better readability
  bg = "#000000",  -- Inverted from white to black
  alt_fg = "#00AAAA",  -- Kept original
  alt_bg = "#222222",  -- Darkened for dark theme
  cursorline = "#222222",  -- Adjusted for dark theme
  line = "#333333",  -- Adjusted for dark theme
  dark_gray = "#555555",  -- Kept original
  gray = "#888888",  -- Lightened for better visibility
  context = "#888888",  -- Lightened for better visibility
  light_gray = "#AAAAAA",  -- Kept original
  red = "#FF0000",  -- Brightened from original
  blue = "#0088FF",  -- Adjusted for visibility
  green = "#00FF00",  -- Brightened from original
  cyan = "#00AAAA",  -- Kept original
  orange = "#FF7700",  -- Brightened from original
  yellow = "#FFFF55",  -- Kept original
  purple = "#FF00FF",  -- Brightened from original
  magenta = "#FF00FF",  -- Brightened from original
  cursor_fg = "#000000",  -- Inverted for dark theme
  cursor_bg = "#FFFFFF",  -- Inverted for dark theme
  sign_add = "#00FF00",  -- Brightened for visibility
  sign_change = "#0088FF",  -- Adjusted for visibility
  sign_delete = "#FF0000",  -- Brightened for visibility
  sign_add_alt = "#00FFAA",  -- Adjusted for visibility
  sign_change_alt = "#FFFF00",  -- Adjusted for visibility
  error = "#FF0000",  -- Brightened for visibility
  warn = "#FFAA00",  -- Adjusted for visibility
  info = "#00FF00",  -- Brightened for visibility
  hint = "#0088FF",  -- Adjusted for visibility
  error_bg = "#331111",  -- Dark red background
  warn_bg = "#332211",  -- Dark orange background
  info_bg = "#113311",  -- Dark green background
  hint_bg = "#112233",  -- Dark blue background
  reference = "#333333",  -- Adjusted for dark theme
  success_green = "#00FF00",  -- Brightened for visibility
  folder_blue = "#0088FF",  -- Adjusted for visibility
  ui_blue = "#0088FF",  -- Adjusted for visibility
  ui2_blue = "#0066CC",  -- Adjusted for visibility
  ui3_blue = "#0088FF",  -- Adjusted for visibility
  ui4_blue = "#00AAFF",  -- Adjusted for visibility
  ui5_blue = "#0066FF",  -- Adjusted for visibility
  ui_orange = "#FF7700",  -- Brightened for visibility
  ui2_orange = "#FF5500",  -- Adjusted for visibility
  ui_purple = "#FF00FF",  -- Brightened for visibility
}

return colors
